title: str(required=True)
url: str(required=True, regex='^https?://[\\w.-]+(?:\\.[\\w\\.-]+)+[/\\w\\.-]*$')
desc: str(required=True)
owner: str(required=True)
contact: map(required=True)
contact:
  email: str(required=False, regex='^[\\w\\.-]+@[\\w\\.-]+\\.[a-zA-Z]{2,}$')
  discord: str(required=False, regex='^@\\w{2,32}#\\d{4}$')
  telegram: str(required=False, regex='^@\\w{5,32}$')
