name: Consolidate YAML Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  consolidate_yaml:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Consolidate YAML files
        uses: mikefarah/yq@v4
        with:
          cmd: yq eval-all '. as $item ireduce ([]; . + [$item])' providers/*.yaml > providers.yaml

      - name: Upload providers.yaml as artifact
        uses: actions/upload-artifact@v4
        with:
          path: providers.yaml

      - name: Commit and push consolidated file
        if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update providers.yaml"
          file_pattern: providers.yaml
