name: Validate providers YAMLs

on:
  pull_request:
    paths:
      - 'providers/**/*.yaml'

jobs:
  validate_yaml:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Yamale
        run: |
          pip install yamale

      - name: Validate YAML against schema
        run: |
          for file in providers/*.yaml; do
            yamale -s schema.yaml "$file" || exit 1
          done
